[package]
name = "onoff"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "parse_benchmark"
harness = false

[dev-dependencies]
criterion = "0.3.5"
off_rs = { git = "https://github.com/michidk/off-rs" }
